import {
	Role,
	User,
	UserSession,
	OwnerProfile,
	AgentProfile,
	AgentCoverageCity,
	KycVerification,
	City,
	Amenity,
	PropertyType,
	Property,
	Listing,
	StayPricingTier,
	PropertyMedia,
	PropertyAmenity,
	Inquiry,
	Conversation,
	Message,
	AgentAssignment,
	Review,
	Notification
} from '../models';
import { MsSqlConstants } from './constants.mssql';

export const models = [
	Role,
	User,
	UserSession,
	OwnerProfile,
	AgentProfile,
	City,
	Amenity,
	PropertyType,
	AgentCoverageCity,
	KycVerification,
	Property,
	Listing,
	StayPricingTier,
	PropertyMedia,
	PropertyAmenity,
	Inquiry,
	Conversation,
	Message,
	AgentAssignment,
	Review,
	Notification
];

export const msSqlDBModelsProvider = [
	{ provide: MsSqlConstants.ROLES, useValue: Role },
	{ provide: MsSqlConstants.USERS, useValue: User },
	{ provide: MsSqlConstants.USER_SESSIONS, useValue: UserSession },
	{ provide: MsSqlConstants.OWNER_PROFILES, useValue: OwnerProfile },
	{ provide: MsSqlConstants.AGENT_PROFILES, useValue: AgentProfile },
	{ provide: MsSqlConstants.AGENT_COVERAGE_CITIES, useValue: AgentCoverageCity },
	{ provide: MsSqlConstants.KYC_VERIFICATIONS, useValue: KycVerification },
	{ provide: MsSqlConstants.CITIES, useValue: City },
	{ provide: MsSqlConstants.AMENITIES, useValue: Amenity },
	{ provide: MsSqlConstants.PROPERTY_TYPES, useValue: PropertyType },
	{ provide: MsSqlConstants.PROPERTIES, useValue: Property },
	{ provide: MsSqlConstants.LISTINGS, useValue: Listing },
	{ provide: MsSqlConstants.STAY_PRICING_TIERS, useValue: StayPricingTier },
	{ provide: MsSqlConstants.PROPERTY_MEDIA, useValue: PropertyMedia },
	{ provide: MsSqlConstants.PROPERTY_AMENITIES, useValue: PropertyAmenity },
	{ provide: MsSqlConstants.INQUIRIES, useValue: Inquiry },
	{ provide: MsSqlConstants.CONVERSATIONS, useValue: Conversation },
	{ provide: MsSqlConstants.MESSAGES, useValue: Message },
	{ provide: MsSqlConstants.AGENT_ASSIGNMENTS, useValue: AgentAssignment },
	{ provide: MsSqlConstants.REVIEWS, useValue: Review },
	{ provide: MsSqlConstants.NOTIFICATIONS, useValue: Notification }
];
