export enum Tables {
	Roles = 'Roles',
	Users = 'Users',
	UserSessions = 'UserSessions',
	OwnerProfiles = 'OwnerProfiles',
	AgentProfiles = 'AgentProfiles',
	AgentCoverageCities = 'AgentCoverageCities',
	KycVerifications = 'KycVerifications',
	Cities = 'Cities',
	Amenities = 'Amenities',
	PropertyTypes = 'PropertyTypes',
	Properties = 'Properties',
	Listings = 'Listings',
	StayPricingTiers = 'StayPricingTiers',
	PropertyMedia = 'PropertyMedia',
	PropertyAmenities = 'PropertyAmenities',
	Inquiries = 'Inquiries',
	Conversations = 'Conversations',
	Messages = 'Messages',
	AgentAssignments = 'AgentAssignments',
	Reviews = 'Reviews',
	Notifications = 'Notifications'
}
